version: "3.3"

services:
  #-------------------Patient
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_PASSWORD: "rootroot"
      MYSQL_ROOT_PASSWORD: "rootroot"
      MYSQL_DATABASE: "patient"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/data/db

  patient:
    #    image: patient_ms
    build: PatientMS/.
    container_name: patient_ms
    #restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patient
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "rootroot"
    #      DATABASE_HOST: mysql
    #      DATABASE_PORT: 3308
    #     DATABASE_NAME: patient
    #      USERNAME: root
    #      PASSWORD: rootroot
    ports:
      - "8081:8081"
  #---------------------NOTE
  notedb:
    image: mongo:5
    container_name: note_db_nosql
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootroot
    ports:
      - "27017:27017"
    volumes:
      - notedb-data:/data/db

  note:
    #    image: note_ms
    build: NoteMS/.
    container_name: note_ms
    restart: always
    depends_on:
      - notedb
    environment:
      SPRING_DATA_MONGODB_HOST: note_db_nosql
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: rootroot
    ports:
      - "8082:8082"
  # ------------------------Assess
  assess:
    #    image: assess_ms
    build: AssessMS/.
    container_name: assess_ms
    restart: always
    depends_on:
      - patient
      - note
    environment:
      - PATIENT_URL=patient:8081
      - NOTE_URL=note:8082
    ports:
      - "8083:8083"

volumes:
  mysql-data:
  notedb-data:
