version: "3.3"

services:
  patientdb:
    image: mysql:8
    container_name: patient_db_sql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: patient_db_sql
    ports:
      - "23306:3306"
    volumes:
      - patientdb_data:/data/db

  patient:
    image: patient_ms
    container_name: patient_ms
    depends_on:
          - patientdb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://patient_db_sql:3306/patient
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootroot
    ports:
      - "8081:8081"

volumes:
    patientdb_data:
