version: "3.3"

services:

  patient:
    build: PatientMS/.
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://patientdb:3306/patient
    depends_on:
      - patientdb
    ports:
      - "8080:8080"
    networks:
      mediscreennetwork:
        ipv4_address: 172.20.0.2

  patientdb:
    image: "mysql:8.0"
    environment:
      - MYSQL_ROOT_PASSWORD=rootroot
      - MYSQL_DATABASE=patient
    ports:
      - "3351:3306"
    networks:
      mediscreennetwork:
        ipv4_address: 172.20.0.3

networks:
  mediscreennetwork:
    ipam:
      config:
        - subnet: 172.20.0.0/16
